apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: department-service
build:
  artifacts:
    - image: piomin/department
      jib:
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - ../k8s/privileges.yaml
    - k8s/**.yaml
